---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-syx6
  namespace: x0c-awxtower-prod
spec:
  
  # Eigentlich Default....
  service_type: ClusterIP

  # Admin User
  admin_user: admin
  admin_password_secret: awx-syx6-admin-password

  # Secret Key
  secret_key_secret: awx-syx6-secret-key 

  # Ingress wird extern via separatem deployment erzeugt
  ingress_type: none

  # Postgres lassen wir den Operator erstellen.
  # Storage Class in der Bedag
  postgres_storage_class: msa-01

  # Logs einschalten
  no_log: false

  # LDAP SSL Cert
  ldap_cacert_secret: awx-syx6-custom-certs

  # LDAP Teil nicht implementiert. Funktioniert zwar, ist dann aber im AWX-GUI
  # nicht mehr aenderbar und das ist muehsam. 
#  ldap_password_secret: awx-syx6-ldap-password

  # Extra Settings
#  extra_settings:
#    - setting: AUTH_LDAP_SERVER_URI
#      value: >-
#        "ldap://mcosrv2005.mgmt.local:389 ldap://mcosrv2006.mgmt.local:389"
#
#    - setting: AUTH_LDAP_BIND_DN
#      value: >-
#        "CN=rh18,OU=Tech-Users,OU=adUsers,DC=mgmt,DC=local"
#
#    - setting: AUTH_LDAP_USER_SEARCH
#      value: 'LDAPSearch("DC=mgmt,DC=local",ldap.SCOPE_SUBTREE,"(sAMAccountName=%(user)s)",)'
#
#    - setting: AUTH_LDAP_GROUP_SEARCH
#      value: 'LDAPSearch("OU=mgmt,DC=local",ldap.SCOPE_SUBTREE,"(objectClass=group)",)'
  
  #------------------------------
  # Persistent Storage
  #------------------------------
  # Damit liegt dan /var/lib/awx/projects auf persistentem Storage im:
  # awx-syx6-task... POD im Container awx-syx6-task
  #      /dev/sdg        2.0G   24K  1.9G   1% /var/lib/awx/projects
  projects_persistence: true
  projects_storage_class: msa-01
  projects_storage_size: 10Gi
  projects_storage_access_mode: ReadWriteOnce
