# ingress-argocd.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-syx6
  namespace: awx-syx6
  annotations:
    kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: nova3.pirate-it.ch
    http:
      paths:
      - pathType: Prefix
        path: /awx
        backend:
          service:
            name: awx-syx6-service
            port:
              number: 80
